In [1]:
from keras.preprocessing.text import one_hot

Using TensorFlow backend.
C:\Users\hp\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\hp\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\hp\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\hp\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarn

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = [  "My name is shrikant",
       "i am studiying in computer science",
       "i wanna be visit manali",
       "i can go as soon as posible", 
       "this is my big dream"]

In [4]:
sent

['My name is shrikant',
 'i am studiying in computer science',
 'i wanna be visit manali',
 'i can go as soon as posible',
 'this is my big dream']

In [5]:
voc_size = 10000

### one hot representation

In [6]:
onehot_repre = [one_hot(words, voc_size) for words in sent]
print(onehot_repre)

[[5649, 5644, 3491, 9142], [7683, 6635, 4029, 9656, 7932, 5242], [7683, 4398, 7210, 4877, 3256], [7683, 5962, 974, 5972, 9059, 5972, 8513], [2202, 3491, 5649, 479, 3789]]


### Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
sent_len = 8
embedded_docs = pad_sequences(onehot_repre, padding='pre', maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 5649 5644 3491 9142]
 [   0    0 7683 6635 4029 9656 7932 5242]
 [   0    0    0 7683 4398 7210 4877 3256]
 [   0 7683 5962  974 5972 9059 5972 8513]
 [   0    0    0 2202 3491 5649  479 3789]]


In [13]:
model=Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_len))
model.compile('adam', 'mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

[[[-2.12938674e-02 -2.25849748e-02 -3.55477221e-02  2.52312087e-02
   -1.96010713e-02 -3.78076658e-02  2.68041752e-02 -2.87449602e-02
    2.69891359e-02  1.74905397e-02]
  [-2.12938674e-02 -2.25849748e-02 -3.55477221e-02  2.52312087e-02
   -1.96010713e-02 -3.78076658e-02  2.68041752e-02 -2.87449602e-02
    2.69891359e-02  1.74905397e-02]
  [-2.12938674e-02 -2.25849748e-02 -3.55477221e-02  2.52312087e-02
   -1.96010713e-02 -3.78076658e-02  2.68041752e-02 -2.87449602e-02
    2.69891359e-02  1.74905397e-02]
  [-2.12938674e-02 -2.25849748e-02 -3.55477221e-02  2.52312087e-02
   -1.96010713e-02 -3.78076658e-02  2.68041752e-02 -2.87449602e-02
    2.69891359e-02  1.74905397e-02]
  [-6.90676272e-04 -4.10157666e-02 -6.51922077e-03  4.14856113e-02
    3.13902013e-02  2.84967087e-02  4.01015766e-02 -3.13239843e-02
   -6.57334179e-03  2.12635882e-02]
  [-3.21536437e-02 -1.11287944e-02 -1.04741082e-02  4.44349311e-02
   -2.33918186e-02  4.93365191e-02  3.60872410e-02 -2.99518351e-02
    3.41282040e-

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 5649, 5644, 3491, 9142])

In [18]:
model.predict(embedded_docs)[0]

array([[-0.02129387, -0.02258497, -0.03554772,  0.02523121, -0.01960107,
        -0.03780767,  0.02680418, -0.02874496,  0.02698914,  0.01749054],
       [-0.02129387, -0.02258497, -0.03554772,  0.02523121, -0.01960107,
        -0.03780767,  0.02680418, -0.02874496,  0.02698914,  0.01749054],
       [-0.02129387, -0.02258497, -0.03554772,  0.02523121, -0.01960107,
        -0.03780767,  0.02680418, -0.02874496,  0.02698914,  0.01749054],
       [-0.02129387, -0.02258497, -0.03554772,  0.02523121, -0.01960107,
        -0.03780767,  0.02680418, -0.02874496,  0.02698914,  0.01749054],
       [-0.00069068, -0.04101577, -0.00651922,  0.04148561,  0.0313902 ,
         0.02849671,  0.04010158, -0.03132398, -0.00657334,  0.02126359],
       [-0.03215364, -0.01112879, -0.01047411,  0.04443493, -0.02339182,
         0.04933652,  0.03608724, -0.02995184,  0.00341282,  0.00188601],
       [ 0.03900261, -0.01103721,  0.00827675,  0.03062152,  0.02149887,
        -0.00826675, -0.04327892, -0.00484097